/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject2;

/**
 *
 * @author joao.ptbasilio
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Loja = new javax.swing.JMenu();
        Cacli = new javax.swing.JMenuItem();
        loja = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Reana = new javax.swing.JMenuItem();
        Resin = new javax.swing.JMenuItem();
        Caprod = new javax.swing.JMenuItem();
        Capord = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Loja.setText("Cliente");

        Cacli.setText("Cadastar Cliente");
        Cacli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CacliActionPerformed(evt);
            }
        });
        Loja.add(Cacli);

        loja.setText("Loja");
        loja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lojaActionPerformed(evt);
            }
        });
        Loja.add(loja);

        jMenuBar1.add(Loja);

        jMenu2.setText("Funcionario");

        Reana.setText("Relatorio Analitico");
        Reana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReanaActionPerformed(evt);
            }
        });
        jMenu2.add(Reana);

        Resin.setText("Relatorio Sintetico");
        Resin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResinActionPerformed(evt);
            }
        });
        jMenu2.add(Resin);

        Caprod.setText("Estoque");
        Caprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaprodActionPerformed(evt);
            }
        });
        jMenu2.add(Caprod);

        Capord.setText("Cadastar Produto");
        Capord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapordActionPerformed(evt);
            }
        });
        jMenu2.add(Capord);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReanaActionPerformed
        
    }//GEN-LAST:event_ReanaActionPerformed

    private void ResinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResinActionPerformed
        
    }//GEN-LAST:event_ResinActionPerformed

    private void CacliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CacliActionPerformed
        TelaC tela = new TelaC();
        tela.setVisible(true);
    }//GEN-LAST:event_CacliActionPerformed

    private void lojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lojaActionPerformed
        TelaCo tela = new TelaCo();
        tela.setVisible(true);
    }//GEN-LAST:event_lojaActionPerformed

    private void CaprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaprodActionPerformed
        TelaEstoque tela = new TelaEstoque();
        tela.setVisible(true);
    }//GEN-LAST:event_CaprodActionPerformed

    private void CapordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapordActionPerformed
        TelaProd tela = new TelaProd();
        tela.setVisible(true);
    }//GEN-LAST:event_CapordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cacli;
    private javax.swing.JMenuItem Capord;
    private javax.swing.JMenuItem Caprod;
    private javax.swing.JMenu Loja;
    private javax.swing.JMenuItem Reana;
    private javax.swing.JMenuItem Resin;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loja;
    // End of variables declaration//GEN-END:variables
}
